### ISSUE TITLE
Implement i18n-js

### ISSUE THREAD

**Issue by ldonis** [lomaxtechnologies/cotizador#13]
Implement [i18n-js](https://github.com/fnando/i18n-js) to use Rails translations within javascript files

https://github.com/lomaxtechnologies/cotizador/blob/b8be9126af6ab28fc054a1aff0af42fcd60b6805/app/javascript/users/registrations/index.js#L1

**Comment by carehs12** [comment]
The issue was solved on branch #23 i18n-js, it has now been marged to master
